name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ["3.0", "3.2"]
        rails: ["7.0", "7.1"]

    env:
      DUMMY_APP_PATH: ${{ github.workspace }}/spec/dummy_apps/rails-${{ matrix.rails }}
      TEST_VERSION: ${{ matrix.rails }}
    steps:
      # https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v3

      # https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # runs `bundle install` and caches gems automatically
        env:
          BUNDLE_GEMFILE: ""

      - name: Install dependencies
        run: cd ${DUMMY_APP_PATH}; bundle install --no-cache

      - name: Run tests
        run: BUNDLE_GEMFILE=spec/dummy_apps/rails-${{ matrix.rails }}/Gemfile TEST_VERSION=${{ matrix.rails }} bundle exec rake
